[2025-10-02T00:43:33.799+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-02T00:43:33.812+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alpha_vantage_to_snowflake.execute_pipeline manual__2025-10-02T00:43:30.544712+00:00 [queued]>
[2025-10-02T00:43:33.818+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alpha_vantage_to_snowflake.execute_pipeline manual__2025-10-02T00:43:30.544712+00:00 [queued]>
[2025-10-02T00:43:33.818+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-02T00:43:33.826+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): execute_pipeline> on 2025-10-02 00:43:30.544712+00:00
[2025-10-02T00:43:33.833+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=272) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-02T00:43:33.834+0000] {standard_task_runner.py:72} INFO - Started process 275 to run task
[2025-10-02T00:43:33.833+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'alpha_vantage_to_snowflake', 'execute_pipeline', 'manual__2025-10-02T00:43:30.544712+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/alpha_vantage_to_snowflake.py', '--cfg-path', '/tmp/tmpsotg9216']
[2025-10-02T00:43:33.835+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask execute_pipeline
[2025-10-02T00:43:33.864+0000] {task_command.py:467} INFO - Running <TaskInstance: alpha_vantage_to_snowflake.execute_pipeline manual__2025-10-02T00:43:30.544712+00:00 [running]> on host dc0cf9892ce9
[2025-10-02T00:43:33.929+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alpha_vantage_to_snowflake' AIRFLOW_CTX_TASK_ID='execute_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T00:43:30.544712+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T00:43:30.544712+00:00'
[2025-10-02T00:43:33.930+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-02T00:43:33.941+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-02T00:43:33.942+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-10-02T00:43:33.943+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-02T00:43:33.944+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-02T00:43:34.524+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-02T00:43:34.767+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-02T00:44:45.335+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-02T00:44:45.335+0000] {logging_mixin.py:190} INFO - Data inserted successfully into Snowflake table
[2025-10-02T00:44:45.336+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-02T00:44:45.344+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-02T00:44:45.345+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=alpha_vantage_to_snowflake, task_id=execute_pipeline, run_id=manual__2025-10-02T00:43:30.544712+00:00, execution_date=20251002T004330, start_date=20251002T004333, end_date=20251002T004445
[2025-10-02T00:44:45.365+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-02T00:44:45.377+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-02T00:44:45.379+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
